name: daily
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: 1.1.0
  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.0
  intl: 0.18.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/loginbar.svg
    - assets/sucess.svg
    - assets/avatar.svg
    - assets/happy.svg
    - assets/raccoon.svg
    - assets/raccon_logo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
  uses-material-design: true
