name: daily
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.0
  intl: 0.18.1
  shared_preferences: ^2.2.3
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  audioplayers: ^5.1.0
  iconsax: ^0.0.8
  flutter_modular: ^6.3.3
  provider: ^6.1.2
  flutter_dash: ^1.0.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  dashed_line: ^0.1.0+3
  syncfusion_flutter_gauges: 24.2.5
  flutter_bloc: ^8.1.6
  numberpicker: ^2.1.2
  image_picker: ^1.0.8
  flutter_gemini: ^2.0.5
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/loginbar.svg
    - assets/logo.png
    - assets/sucess.svg
    - assets/raccon_logo.png
    - assets/raccoon.svg
    - assets/atencaoplena.mp3
    - assets/vipassana.mp3
    - assets/respiracaoserena.mp3
    - assets/mentetranquila.mp3
    - assets/pazinterior.mp3
    - assets/profunda.mp3
    - assets/progressivo.mp3
    - assets/compaixao.mp3
    - assets/stress.mp3
    - assets/emoji_felicidade.png
    - assets/emoji_tristeza.png
    - assets/meta_concluida.png
    - assets/registro_concluido.png
    - assets/chat.png
    - assets/emoji_normal.png
    - assets/emoji_muito_feliz.png
    - assets/emoji_bravo.png
    - assets/article_illustration.png
    - assets/article_illustration2.png
    - assets/article_illustration3.png
    - assets/article_illustration4.png
    - assets/article_illustration5.png
    - assets/article_illustration6.png
    - assets/m1.png
    - assets/m2.png
    - assets/m3.png
    - assets/m4.png
    - assets/m5.png
    - assets/m6.png
    - assets/m7.png
    - assets/m8.png
    - assets/m9.png
    - assets/m10.png
    - assets/may.png
    - assets/emoji_not_found.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
    - family: Pangram
      fonts:
        - asset: assets/fonts/Pangram-Regular.otf
          style: normal
    - family: Pangram
      fonts:
        - asset: assets/fonts/Pangram-Bold.otf
          style: normal
  uses-material-design: true
assets/m1:
  png:
