name: daily
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: 1.1.0
  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.0
  intl: 0.18.1
  shared_preferences: ^2.2.3
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  iconsax: ^0.0.8
  flutter_modular: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/loginbar.svg
    - assets/sucess.svg
    - assets/raccon_logo.png
    - assets/emoji_felicidade.png
    - assets/emoji_ansiedade.png
    - assets/emoji_tedio.png
    - assets/emoji_tristeza.png
    - assets/emoji_confusao.png
    - assets/emoji_animacao.png
    - assets/emoji_decepcao.png
    - assets/emoji_foco.png
    - assets/emoji_apatico.png
    - assets/emoji_surpresa.png
    - assets/emoji_cansaso.png
    - assets/emoji_motivado.png
    - assets/sun.png
    - assets/clear.png
    - assets/cold.png
    - assets/cloudy.png
    - assets/rainy.png
    - assets/tempestade.png
    - assets/emoji_not_found.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
    - family: Pangram
      fonts:
        - asset: assets/fonts/Pangram-Regular.otf
          style: normal
    - family: Pangram
      fonts:
        - asset: assets/fonts/Pangram-Bold.otf
          style: normal
  uses-material-design: true
